import React from 'react'

const Exmpl = () => {
  return (
    <div>ExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmplExmpl</div>
  )
}

export default Exmpl